email = "chianews@b8.lv"
#facebook = "yourfacebookusername"
github = "speedmann"
#gitlab = "yourgitlabusername"
#linkedin = "yourlinkedinusername"
#stackoverflow = "yourstackoverflowuserid"
twitter = "speedmannde"
#weibo = "yourweibousername"
#zhihu = "yourzhihuusername"
#instagram = "yourinstagramusername"
#quora = "yourquorausername"
#tumblr = "yourtumblrusername"
reddit = "speedmann"
#telegram = "yourtelegramusername"
#qq = "yourqqnumber"
#dockerhub = "yourdockerhubusername"
#bitbucket = "yourbitbucketworkspaceid"
#medium = "yourmediumusername" # Medium username or custom domain(e.g. https://custom.domain.tld).
#lastfm = "yourlastfmusername"
#bilibili = "yourbilibiliuserid"
